apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wandercult
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: aliouimohamedamine/wandercult:latest  #changer to your Docker Hub username
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/auth_Wandercult
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GOOGLE_CLIENT_SECRET
