apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: wandercult
type: Opaque
stringData:
  GOOGLE_CLIENT_ID:  # Replace with your actual Google Client ID
  GOOGLE_CLIENT_SECRET: # Replace with your actual Google Client Secret
